services:
  - type: web
    name: user-management-system
    env: node
    buildCommand: |
      npm install -g @angular/cli
      npm install
      npm run build
    startCommand: node node-mysql-boilerplate-api/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: u875409848_ocliasa
      - key: DB_PASSWORD
        sync: false  # This will prompt you to set it in Render dashboard
      - key: DB_NAME
        value: u875409848_ocliasa