services:
  - type: web
    name: user-management-system
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.13.1
      - key: DATABASE_URL
        fromDatabase:
          name: mysql
          property: connectionString

databases:
  - name: mysql
    ipAllowList: []